version: '3'
services:
  lizmap:
    image: 3liz/lizmap-web-client:3.2
    environment:
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      LIZMAP_USER: ${LIZMAP_USER_ID}
      LIZMAP_WMSSERVERURL: http://web:7000
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${LIZMAP_DIR}/var/lizmap-config:/www/lizmap/var/config
      - ${LIZMAP_DIR}/var/lizmap-db:/www/lizmap/var/db
      - ${LIZMAP_DIR}/www:/www/lizmap/www
      - ${LIZMAP_DIR}/www/var/log:/www/lizmap/var/log
    command:
      - php-fpm
    restart: unless-stopped
  qgis:
    image: 3liz/qgis-platform:2.18
    environment:
      QGIS_USER: ${LIZMAP_USER_ID}
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
    command:
      - run-qgis-server
    working_dir: /srv/projects
    restart: unless-stopped
  redis:
    image: redis:5
  web:
    image: nginx:1
    volumes:
      - ${LIZMAP_DIR}/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${LIZMAP_DIR}/var/log/nginx:/var/log/nginx
      - ${LIZMAP_DIR}:/srv/lizmap
    expose:
      - "80"
      - "7000"
    ports:
      - 8888:80
      - 7000:7000

