version: '3'
networks:
  picnet:
    external: true
services:
  pgsql:
    image: 3liz/postgis:${POSTGIS_VERSION_TAG}
    environment:
      POSTGRES_DB: lizmap
      POSTGRES_PASSWORD: NpAG38b1*1PBS&I#
      POSTGRES_USER: lizmapuser
    volumes:
      - ${LIZMAP_DIR}/pg_data:/var/lib/postgresql/data
      - ${LIZMAP_DIR}/pg_run:/var/run/postgresql
    ports:
      - ${LIZMAP_POSTGRESQL_PORT}:5432
    networks:
      default:
        aliases:
          - db.lizmap.local
  lizmap:
    image: 3liz/lizmap-web-client:${LIZMAP_VERSION_TAG}
    environment:
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      LIZMAP_USER: ${LIZMAP_USER_ID}
      LIZMAP_WMSSERVERURL: http://map:8080/ows/
      LIZMAP_WPS_URL: http://wps:8080/

    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${LIZMAP_DIR}/var/lizmap-config:/www/lizmap/var/config
      - ${LIZMAP_DIR}/var/lizmap-db:/www/lizmap/var/db
      - ${LIZMAP_DIR}/www:/www/lizmap/www
      - ${LIZMAP_DIR}/www/var/log:/www/lizmap/var/log
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
    command:
      - php-fpm
    restart: unless-stopped
  map:
    image: 3liz/qgis-map-server:${QGIS_VERSION_TAG}
    environment:
      QGSRV_CACHE_SIZE: '20'
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_USER: ${LIZMAP_USER_ID}:${LIZMAP_USER_GID}
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_SERVER_WORKERS: ${QGIS_MAP_WORKERS}
      QGSRV_SERVER_PLUGINPATH: /srv/plugins
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGSPASSFILE: /srv/etc/pgpass.conf
      QGIS_OPTIONS_PATH: /srv/etc/qgis
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
      - ${LIZMAP_DIR}/wps-data:/srv/data
    ports:
      - ${OWS_PORT}:8080
    restart: unless-stopped
  redis:
    image: redis:5-alpine
  web:
    image: nginx:1
    user: ${LIZMAP_USER_ID}:${LIZMAP_USER_ID}
    volumes:
      - ${LIZMAP_DIR}/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${LIZMAP_DIR}/var/log/nginx:/var/log/nginx
      - ${LIZMAP_DIR}/var/nginx-cache:/var/cache/nginx
      - ${LIZMAP_DIR}:/srv/lizmap
    environment:
            VIRTUAL_HOST: carto2p2r.picttn.le-pic.org,velomax.picttn.le-pic.org
            VIRTUAL_PORT: "8080"
    networks:
        - picnet
        - default
    ports:
        - ${LIZMAP_PORT}:8080
    depends_on:
      - lizmap
